### ISSUE TITLE
CBI学会2024年大会ケモインフォマティクスハンズオン参加時に追加で必要だった操作・質問

### ISSUE THREAD

**Issue by AunderbTommy888** [cbi-society/cheminfo_tutorial_20241028_pub#1]
楽しい会をありがとうございました。
下記でドキュメント以外に当日追加で動作させるために行った操作の報告と質問をさせてください。

外部GPUサーバー上のnotebookで作業を行っていたため、環境変数はnotebook上で設定しました。
```
import os
os.environ['XDG_CONFIG_HOME'] = '{where your maize.toml placed}'

```
reinvent4を動作させるためにreinvent4の動作環境で下記のパッケージをインストールしました。
```
conda install -c conda-forge python-xxhash -n reinvent4
{path_to_miniconda3}/envs/reinvent4/bin/pip install pandas mmpdb tqdm pathos pydantic tomli requests scipy tensorboard molvs rdkit

```
torchは記載の通りにするとpypiからcpuの方が入ってきてしまったので下記で雑にcuda対応のものを入れました。
`conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia -n reinvent4`

質問
06_Build_SBDD_WF.ipynbで高速化のために`from maize.steps.mai.docking.adv import Vina
`の代わりに`from maize.steps.mai.docking.adv import VinaGPU`を利用しようとしたのですが、exhaustivenessの代わりにthreadなどの指定をしようと思ったら指定することができませんでした。おすすめの設定や実際のサンプルコードなどがあったら拝見したいです。よろしくお願いいたします。

**Comment by iwatobipen** [comment]
この度はチュートリアルご参加ありがとうございました！
環境変数とパッケージの部分は当日も多くの方でトラブルがあったので上記の部分確認し更新するようにいたします。ありがとうございます。
またVinaGPUノードですが
ご指摘いただいた部分はソースを見るとハードコーディングされていました。
https://github.com/MolecularAI/maize-contrib/blob/0bb116903387bf2680dd90a1d681584c159a8506/maize/steps/mai/docking/adv.py#L1428
            f"--thread 8000 --seed {self.seed.value} "
従いましてここを書き換えるのが一番ダイレクトな方法。
または、上記のノードをベースにオリジナルのVinaGPUv2ノードを定義しそこでthreadなど指定したいものをパラメータとするのがいいのかなと思いました。

**Comment by AunderbTommy888** [comment]
ありがとうございます！
thread 8000なら十分かなとも思いますが、せっかくなので勉強も兼ねてVinaGPUv2ノードを書いてみたいと思います！

**Comment by iwatobipen** [comment]
ubuntuのインストール手順の記載にミスが有りました。大変申し訳ありません。
ご指摘のとおり当初の手順だとGPU利用できない環境ができてしまいます。
https://github.com/cbi-society/cheminfo_tutorial_20241028_pub
ご迷惑をおかけしてしまい大変申し訳ありませんでした。
修正しました。
